import { collection, query, where, getDocs, doc, updateDoc, Timestamp, arrayUnion } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { generateText } from "@/lib/gemini";
import { sendOfficialComplaintEmail } from "@/lib/resend";

/**
 * Scans Firestore for unresolved issues older than 48 hours and runs negotiation automation.
 */
export async function runNegotiationAgent(): Promise<number> {
  let processedCount = 0;
  try {
    const issuesRef = collection(db, "issues");
    const fortyEightHoursAgo = new Date();
    fortyEightHoursAgo.setHours(fortyEightHoursAgo.getHours() - 48);

    // Get all unresolved issues created more than 48 hours ago
    const q = query(
      issuesRef,
      where("status", "in", ["Reported", "Verified", "Escalated", "Assigned"]),
      where("createdAt", "<=", Timestamp.fromDate(fortyEightHoursAgo))
    );

    const querySnapshot = await getDocs(q);

    for (const docSnapshot of querySnapshot.docs) {
      const issue = { id: docSnapshot.id, ...docSnapshot.data() } as any;

      // Avoid spamming: only negotiate once every 48 hours
      if (issue.lastNegotiationAt) {
        const lastNegotiation = issue.lastNegotiationAt.toDate();
        const differenceInHours = (new Date().getTime() - lastNegotiation.getTime()) / (1000 * 60 * 60);
        if (differenceInHours < 48) {
          continue;
        }
      }

      // Run AI Negotiation for this issue
      await negotiateIssue(issue);
      processedCount++;
    }
  } catch (error) {
    console.error("Error in AI Negotiation Agent scanning:", error);
  }
  return processedCount;
}

/**
 * Generates an official complaint letter for an issue and sends it.
 */
export async function negotiateIssue(issue: any): Promise<void> {
  const deptEmail = getDepartmentEmail(issue.category);
  const deptName = getDepartmentName(issue.category);
  
  const systemPrompt = `You are the CivicPulse AI Public Negotiation Agent. Your role is to write highly professional, formal, and assertive letters of complaint to local municipal departments advocating on behalf of citizens. Use an official, respectful, yet firm tone. Include references to public safety and community well-being.`;
  
  const prompt = `Draft a formal letter of complaint to the ${deptName} (${deptEmail}) regarding the following unresolved issue:
  - Issue ID: ${issue.id}
  - Category: ${issue.category} (Subcategory: ${issue.subcategory || "N/A"})
  - Location: ${issue.address}
  - Description: ${issue.description}
  - Severity Level: ${issue.severity}/10
  - Root Cause Hypothesis: ${issue.rootCause || "General infrastructure failure"}
  - Affected Community Estimate: ${issue.affectedPopulation || "Multiple residents"}
  
  Explain that this issue has remained unresolved for over 48 hours, causing significant public inconvenience and safety hazards. Request a target completion date and detail how the progress will be tracked publicly on the CivicPulse portal. Output ONLY the letter text.`;

  try {
    const complaintLetter = await generateText(prompt, systemPrompt);

    // Send email using Resend
    const subject = `URGENT: Municipal Redressal Request - Issue #${issue.id} (${issue.category.toUpperCase()})`;
    const htmlBody = `
      <div style="font-family: Arial, sans-serif; padding: 20px; color: #333; line-height: 1.6;">
        <h2 style="color: #d32f2f;">CivicPulse Municipal Complaint System</h2>
        <hr style="border: 0; border-top: 1px solid #ccc;" />
        <pre style="white-space: pre-wrap; font-family: inherit; font-size: 14px;">${complaintLetter}</pre>
        <br />
        <p style="font-size: 12px; color: #777;">
          This email was auto-generated by the CivicPulse AI Negotiation Agent. Replies to this email will be ingested and analysed publicly.
        </p>
      </div>
    `;

    const emailResponse = await sendOfficialComplaintEmail(deptEmail, subject, htmlBody);

    if (emailResponse.success) {
      const issueDocRef = doc(db, "issues", issue.id);

      const logEntry = {
        timestamp: Timestamp.now(),
        message: `Official complaint successfully dispatched to ${deptName} (${deptEmail}). AI negotiation initiated.`,
        sender: "AI Agent" as const,
      };

      await updateDoc(issueDocRef, {
        status: "Escalated", // Auto-escalate once negotiation starts
        lastNegotiationAt: Timestamp.now(),
        negotiationLog: arrayUnion(logEntry),
        timeline: arrayUnion({
          status: "Escalated",
          updatedBy: "AI Negotiation Agent",
          updatedAt: Timestamp.now(),
          comment: `Escalated directly to ${deptName} via Resend Email. Ref: ${emailResponse.id || "N/A"}`
        })
      });
    }
  } catch (error) {
    console.error(`Failed to negotiate issue ${issue.id}:`, error);
  }
}

function getDepartmentEmail(category: string): string {
  const mapping: Record<string, string> = {
    pothole: "potholes.pwd@civicpulse.gov",
    drain: "drainage.sewage@civicpulse.gov",
    light: "streetlights.electricity@civicpulse.gov",
    water: "waterworks.supply@civicpulse.gov",
    garbage: "sanitation.waste@civicpulse.gov",
    construction: "encroachments.building@civicpulse.gov",
  };
  return mapping[category] || "support@civicpulse.gov";
}

function getDepartmentName(category: string): string {
  const mapping: Record<string, string> = {
    pothole: "Public Works (Roads) Department",
    drain: "Stormwater Drainage & Sewerage Board",
    light: "Municipal Lighting & Electricity Department",
    water: "Hydraulics & Water Supply Department",
    garbage: "Solid Waste Management Division",
    construction: "Urban Planning & Construction Monitoring Dept",
  };
  return mapping[category] || "Municipal Redressal Commission";
}
